# The config file of GDAS : https://arxiv.org/abs/1910.04465
SPACE:
  NAME: 'gdas'
  NUM_CLASSES: 10
  CHANNEL: 16
  LAYERS: 8
  NODES: 4
# SPACE: # Model-config which reach BEST result in original paper
#   NAME: 'gdas'
#   NUM_CLASSES: 10
#   CHANNEL: 32
#   LAYERS: 20
#   NODES: 4
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
  IM_SIZE: 32
OPTIM:
  MAX_EPOCH: 50
OUT_DIR: '/userhome/project/XNAS/experiment/gdas'